### ISSUE TITLE
Requirement not satisfied

### ISSUE THREAD

**Issue by kdsjZh** [tyukiand/asm2cfg#1]
I found your project very helpful but i failed to install because of the lib tycoll.

I try to install it by apt,and i searched it in github,but i found nothing.
so can you tell me where can i get this lib?

**Comment by tyukiand** [comment]
@kdsjZh Indeed, it doesn't build! The `tycoll` library contained some basic collections, lists and hashmaps mainly, and they used to be in a separate library. Later, I moved them into asm2cfg, but didn't update the Makefile. This should be fixed now. Thanks.
